In [2]:
import numpy as np
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
a.shape

(10,)

In [4]:
b = np.linspace(2, 3, 5)  # From 2 to 3, with 5 elements
print(b)

[2.   2.25 2.5  2.75 3.  ]


In [5]:
a_list = [1,2,3,4,5,6,7]
z = np.array([a_list])
print(z)
type(z)

[[1 2 3 4 5 6 7]]


numpy.ndarray

In [6]:
n1=np.array([10,20,30,40])
print(n1)
type(n1)

[10 20 30 40]


numpy.ndarray

In [7]:
n2=np.array([[1,2,3,4],[5,6,7,8]])
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# Initializing NumPy array with zeros
n3=np.zeros((2,3)) # 2 rows, 3 columns
print(n3)
type(n3)

[[0. 0. 0.]
 [0. 0. 0.]]


numpy.ndarray

In [9]:
# Initializing NumPy array with same number
n4=np.full((2,2),10) # 2x2 with value 10
n4

array([[10, 10],
       [10, 10]])

In [10]:
# Initializing NumPy array within a range
n5=np.arange(10,20) # values from 10 till 20
print(n5)

n6=np.arange(10,20,2) # values from 10 till 20 with interval of 2
print(n6)

[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [11]:
# Initializing NumPy array with random numbers
n7=np.random.randint(1,100,10) # generate 5 random values between 1-100
print(n7)

[60 24 33 43 26 90 72 85 62 22]


In [12]:
# Checking the shape of NumPy array
n8=np.array([[1,2,3,4],[5,6,7,8]])
print(n8)
print(n8.shape) # no. of row and no. of columns

# Inverting the shape of the array
n8.shape=(4,2) # change the shape of the array
print(n8)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
# Joining NumPy arrays
# vstack(), vertical stacking
n9=np.array([10,20,30])
n10=np.array([50,60,70])

print(np.vstack((n9,n10)))

# hstack(), horizontal stacking
n11=np.array([5,10,15])
n12=np.array([20,25,30])

print(np.hstack((n11,n12)))

# cloumn_stack(), convert rows to column
n13=np.array([1,2,3])
n14=np.array([4,5,6])

print(np.column_stack((n13,n14)))



[[10 20 30]
 [50 60 70]]
[ 5 10 15 20 25 30]
[[1 4]
 [2 5]
 [3 6]]


In [14]:
# NumPy Intersection and Difference

# intersection is used to find common elements in the array
n15=np.array([10,20,30,40,50,60])
n16=np.array([40,50,60,70])

print(np.intersect1d(n15,n16))

# difference is used to find different elements in the array
print(np.setdiff1d(n15,n16)) # gives different element of n15 from n16
print(np.setdiff1d(n16,n15)) # gives different element of n16 from n15

[40 50 60]
[10 20 30]
[70]


In [15]:
# NumPy Array Mathematics

# Addition of NumPy Arrays
n17=np.array([10,20,30])
n18=np.array([40,50,60])
print(np.sum([n17,n18]))

# Adding column elements
print(np.sum([n17,n18],axis=0))

# Adding row elements
print(np.sum([n17,n18],axis=1))

# Basic Addition, similarly subtraction, multiplication and division
n17=n17+1
print(n17)

# Mean
print(np.mean(n18))

# Standard Deviation
print(np.std(n18))

# Median
print(np.median(n18))

210
[50 70 90]
[ 60 150]
[11 21 31]
50.0
8.16496580927726
50.0


In [16]:
# NumPy Array save and load

# Saving NumPy Array
n19=np.array([10,20,35,45])
np.save('my_numpy',n19)

# Loading NumPy Array
n20=np.load('my_numpy.npy')
print(n20)

[10 20 35 45]
